"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import styles from "./canastio-market.module.css";
export type MarketPlayer={playerRegistrationId:string;playerId:string;displayName:string;realTeamName:string;competitionName:string;status?:string;currentPrice:number;previousPrice:number|null;changeCredits:number;changePercent:number|null;trend:"UP"|"DOWN"|"FLAT";allTimeHigh:number;allTimeLow:number;averageFantasyPoints:number|null;recentFantasyPoints:readonly number[];owner:{ownerName:string;isMine:boolean;acquisitionPrice:number;clauseInvestment:number}|null;clauseCredits:number|null};
type MarketMeta={leagueId:string;leagueName:string;balanceCredits:number;clausesOpen:boolean;clauseCutoffAt:string};
const money=new Intl.NumberFormat("es-ES",{notation:"compact",maximumFractionDigits:2});
export function CanastioMarket({players,updatedAt,market}:{players:readonly MarketPlayer[];updatedAt?:string;market:MarketMeta}){
 const [query,setQuery]=useState("");const [trend,setTrend]=useState<"ALL"|MarketPlayer["trend"]>("ALL");const [team,setTeam]=useState("ALL");const [price,setPrice]=useState("ALL");const [ownership,setOwnership]=useState("ALL");const [message,setMessage]=useState("");const [pending,setPending]=useState("");
 const teams=useMemo(()=>[...new Set(players.map(p=>p.realTeamName))].sort((a,b)=>a.localeCompare(b,"es")),[players]);
 const visible=useMemo(()=>players.filter(p=>{const priceOk=price==="ALL"||(price==="UNDER_5"&&p.currentPrice<5e6)||(price==="5_TO_10"&&p.currentPrice>=5e6&&p.currentPrice<=1e7)||(price==="OVER_10"&&p.currentPrice>1e7);const ownerOk=ownership==="ALL"||(ownership==="FREE"&&!p.owner)||(ownership==="MINE"&&p.owner?.isMine)||(ownership==="RIVAL"&&p.owner&&!p.owner.isMine);return `${p.displayName} ${p.realTeamName}`.toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))&&(trend==="ALL"||p.trend===trend)&&(team==="ALL"||p.realTeamName===team)&&priceOk&&ownerOk}),[players,query,trend,team,price,ownership]);
 async function transact(player:MarketPlayer,action:"BUY"|"SELL"|"CLAUSE"|"INVEST"|"SHIELD"){let credits:number|undefined;if(action==="INVEST"){const value=prompt("Créditos que quieres invertir");if(!value)return;credits=Number(value);if(!Number.isSafeInteger(credits)||credits<=0)return setMessage("Introduce una cantidad entera válida.");}const amount=action==="CLAUSE"?player.clauseCredits:action==="BUY"||action==="SELL"?player.currentPrice:null;if(!confirm(`${action==="BUY"?"Comprar":action==="SELL"?"Vender":action==="CLAUSE"?"Pagar la cláusula de":action==="SHIELD"?"Blindar":"Aumentar la cláusula de"} ${player.displayName}${amount?` por ${money.format(amount)} créditos`:""}?`))return;setPending(player.playerRegistrationId+action);setMessage("");const response=await fetch("/api/fantasy/market",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({leagueId:market.leagueId,playerRegistrationId:player.playerRegistrationId,action,credits,idempotencyKey:crypto.randomUUID()})});const body=await response.json();setPending("");if(!response.ok)return setMessage(body.error?.code??"No se pudo completar la operación");location.reload();}
 return <main className={styles.market}><header className={styles.header}><div><p className={styles.eyebrow}>{market.leagueName} · {players[0]?.competitionName}</p><h1>La Bolsa Canastio</h1><p>Saldo {money.format(market.balanceCredits)} · Clausulazos {market.clausesOpen?"abiertos":"cerrados"}. La popularidad no altera la cotización.</p></div><div className={styles.ticker}><span>Jugadores</span><strong>{players.length}</strong><small>{updatedAt?`Actualizado ${new Date(updatedAt).toLocaleDateString("es-ES")}`:"Calibración · 5 M"}</small></div></header>
 <section className={styles.controls} aria-label="Filtros de mercado"><label className={styles.search}><span>Buscar</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Jugador o equipo…"/></label><label><span>Equipo</span><select value={team} onChange={e=>setTeam(e.target.value)}><option value="ALL">Todos</option>{teams.map(name=><option key={name}>{name}</option>)}</select></label><label><span>Precio</span><select value={price} onChange={e=>setPrice(e.target.value)}><option value="ALL">Cualquiera</option><option value="UNDER_5">Menos de 5 M</option><option value="5_TO_10">5–10 M</option><option value="OVER_10">Más de 10 M</option></select></label><label><span>Propiedad</span><select value={ownership} onChange={e=>setOwnership(e.target.value)}><option value="ALL">Todos</option><option value="FREE">Libres</option><option value="MINE">Mi equipo</option><option value="RIVAL">Rivales</option></select></label><div role="group" aria-label="Tendencia">{(["ALL","UP","DOWN","FLAT"] as const).map(value=><button key={value} data-active={trend===value} onClick={()=>setTrend(value)}>{value==="ALL"?"Todos":value==="UP"?"Suben":value==="DOWN"?"Bajan":"Estables"}</button>)}</div></section>
 <div className={styles.resultBar}><span>{visible.length} resultados</span><span>Precio</span><span>Estado</span></div>{message&&<p className={styles.message} role="alert">{message}</p>}{visible.length===0?<p className={styles.empty}>No hay jugadores para este filtro.</p>:<ol className={styles.list}>{visible.map((player,index)=><li key={player.playerRegistrationId}><span className={styles.rank}>{String(index+1).padStart(2,"0")}</span><span className={styles.avatar}>{initials(player.displayName)}</span><span className={styles.identity}><Link href={`/app/jugadores/${player.playerId}`}>{player.displayName}</Link><small>{player.realTeamName} · {player.owner?(player.owner.isMine?"Tu plantilla":player.owner.ownerName):"Libre"}</small></span><span className={styles.form}><b>{player.averageFantasyPoints?.toFixed(1)??"—"}</b><small>FP media</small><i>{player.recentFantasyPoints.length?player.recentFantasyPoints.map(s=>s.toFixed(0)).join(" · "):"Sin partidos"}</i></span><strong className={styles.price}>{money.format(player.currentPrice)}</strong><span className={styles.change} data-trend={player.trend}>{player.changePercent===null?"Nuevo":`${player.changePercent>=0?"▲":"▼"} ${Math.abs(player.changePercent).toFixed(1)}%`}</span><span className={styles.marketActions}>{!player.owner?<button disabled={!!pending} onClick={()=>void transact(player,"BUY")}>Comprar</button>:player.owner.isMine?<><button disabled={!!pending} onClick={()=>void transact(player,"SELL")}>Vender</button><button disabled={!!pending} onClick={()=>void transact(player,"SHIELD")}>Blindar</button><button disabled={!!pending} onClick={()=>void transact(player,"INVEST")}>+ Cláusula</button></>:<button disabled={!!pending||!market.clausesOpen} onClick={()=>void transact(player,"CLAUSE")}>Cláusula {player.clauseCredits?money.format(player.clauseCredits):""}</button>}</span></li>)}</ol>}<footer className={styles.note}>El rendimiento deportivo determina el precio; las compras no modifican la cotización.</footer></main>;
}
function initials(name:string){return name.split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase()}
