import Link from "next/link";
import type { HomeDashboard as Dashboard } from "../server/home-dashboard";
import styles from "./home-dashboard.module.css";
const number=new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}),credits=new Intl.NumberFormat("es-ES",{notation:"compact",maximumFractionDigits:2}),date=new Intl.DateTimeFormat("es-ES",{weekday:"short",day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Madrid"});
const copy={READY:"Tu equipo está listo",INCOMPLETE:"Completa tu alineación",NOT_SAVED:"Guarda tu quinteto",LOCKED:"Alineación bloqueada"} as const;
export function HomeDashboard({data}:{data:Dashboard}){if(data.kind!=="READY")return <main className={styles.onboarding}><span>CANASTIO</span><p>Tu temporada empieza aquí</p><h1>Construye tu equipo</h1><p>Crea tu plantilla y únete a una liga para reunir jornadas, mercado y clasificación.</p><Link href="/app/mi-equipo">Empezar ahora <b>→</b></Link></main>;
 const urgent=data.round.lineupState==="INCOMPLETE"||data.round.lineupState==="NOT_SAVED";
 return <main className={styles.page}><header className={styles.top}><Link href="/app" className={styles.brand}>Canastio</Link><div><Link href="/app/ligas" aria-label="Ver actividad de mis ligas">●</Link><Link href="/app/perfil" aria-label="Abrir mi perfil">{(data.displayName??"C")[0].toUpperCase()}</Link></div></header><section className={`${styles.hero} ${urgent?styles.urgent:""}`}><div className={styles.kicker}><span>{data.round.isLive?"● EN DIRECTO":data.round.number?`JORNADA ${String(data.round.number).padStart(2,"0")}`:"PRÓXIMA JORNADA"}</span><span>{data.league.name}</span></div><p>{data.round.cutoffAt?`Cierra ${date.format(new Date(data.round.cutoffAt))}`:"Calendario pendiente de publicación"}</p><h1>{copy[data.round.lineupState]} {data.round.lineupState==="READY"?"✓":""}</h1><div className={styles.heroStats}><strong>{data.performance?number.format(Number(data.performance.points)):"—"}<small> pts</small></strong><span>{data.performance?.position?`${data.performance.position}.ª posición`:"Clasificación pendiente"}</span>{data.performance?.positionChange?<b>{data.performance.positionChange>0?"↑":"↓"} {Math.abs(data.performance.positionChange)} posición</b>:null}</div><Link className={urgent?styles.primaryAction:styles.textAction} href={urgent?"/app/mi-equipo":"/app/jornada"}>{urgent?"Preparar equipo":"Ver jornada"} <b>→</b></Link></section>
 <Section title="Jugadores en movimiento" kicker="Mercado" href="/app/mercado">{data.movers.length?<div className={styles.rows}>{data.movers.map(m=><Link href={`/app/jugadores/${m.id}`} key={m.id}><strong>{m.name}</strong><span>{credits.format(m.price)} cr.</span><b className={m.change>=0?styles.up:styles.down}>{m.change>=0?"▲":"▼"} {Math.abs(m.percentage).toFixed(1)}%<small>{m.change>=0?"+":"−"}{credits.format(Math.abs(m.change))}</small></b></Link>)}</div>:<Empty>Aún no hay dos precios publicados para comparar.</Empty>}</Section>
 <Section title="Próximos partidos" kicker="Agenda">{data.games.length?<div className={styles.fixtures}>{data.games.map(g=><Link href={`/app/partidos/${g.id}`} key={g.id}><time>{g.scheduledAt?date.format(new Date(g.scheduledAt)):"Hora pendiente"}</time><strong>{g.home}<i>vs</i>{g.away}</strong><b>→</b></Link>)}</div>:<Empty>No hay próximos partidos publicados para tu plantilla.</Empty>}</Section>
 <Section title={`Lo último en ${data.league.name}`} kicker="Actividad de la liga" href={`/app/ligas/${data.league.id}`}>{data.activity.length?<ol className={styles.activity}>{data.activity.map(x=><li key={x.id}><i/><p><strong>{x.manager}</strong> {x.type==="SELL"?"vendió a":"fichó a"} <b>{x.player}</b><small>{credits.format(x.price)} créditos · {date.format(new Date(x.createdAt))}</small></p></li>)}</ol>:<Empty>La liga está tranquila. Los próximos movimientos aparecerán aquí.</Empty>}</Section><footer className={styles.updated}>Actualizado {date.format(new Date(data.updatedAt))}</footer></main>}
function Section({title,kicker,href,children}:{title:string;kicker:string;href?:string;children:React.ReactNode}){return <section className={styles.section}><div className={styles.sectionTitle}><div><span>{kicker}</span><h2>{title}</h2></div>{href?<Link href={href}>Abrir →</Link>:null}</div>{children}</section>};function Empty({children}:{children:React.ReactNode}){return <p className={styles.empty}>{children}</p>}
