"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef } from "react";
import { useRouter } from "next/navigation";
import type { JourneyData } from "../server/journey";
import styles from "./journey-live.module.css";

const number=new Intl.NumberFormat("es-ES",{minimumFractionDigits:1,maximumFractionDigits:1});
function ScoreChart({values}:{values:number[]}){const points=useMemo(()=>{const max=Math.max(1,...values);return [[0,96],...values.map((value,index)=>[25+(index*75/Math.max(1,values.length-1)),96-(value/max*78)])].map(pair=>pair.join(",")).join(" ")},[values]);return <figure className={styles.chart}><div><p>Evolución</p><strong>Cómo creció tu jornada</strong></div><svg viewBox="0 0 100 108" role="img" aria-label={`Evolución acumulada: ${values.map(value=>number.format(value)).join(", ")} puntos`} preserveAspectRatio="none"><path className={styles.grid} d="M0 96H100M0 70H100M0 44H100M0 18H100"/><polyline className={styles.line} points={points}/>{values.map((value,index)=>{const max=Math.max(1,...values);return <circle key={index} cx={25+(index*75/Math.max(1,values.length-1))} cy={96-(value/max*78)} r="1.7"/>})}</svg><figcaption>{values.length?`${number.format(values.at(-1)??0)} puntos acumulados por tus titulares.`:"La curva aparecerá cuando puntúe tu quinteto."}</figcaption></figure>}

export function JourneyLive({data}:{data:JourneyData|null}){const router=useRouter();const refreshing=useRef(false);
 useEffect(()=>{if(data?.state!=="LIVE"&&data?.state!=="PROVISIONAL")return;const refresh=()=>{if(document.visibilityState!=="visible"||refreshing.current)return;refreshing.current=true;router.refresh();window.setTimeout(()=>{refreshing.current=false},1500)};const timer=window.setInterval(refresh,30000);return()=>window.clearInterval(timer)},[data?.state,router]);
 if(!data)return <main className={styles.empty}><span aria-hidden="true">05</span><p>Jornada</p><h1>Prepara tu quinteto</h1><strong>Aún no hay un equipo activo para puntuar.</strong><Link href="/app/mi-equipo">Crear mi equipo <b>→</b></Link></main>;
 const scored=data.players.filter(player=>player.state==="FINAL"||player.state==="DNP").length;
 return <main className={styles.page} data-state={data.state}><header className={styles.header}><div><p>{data.competition}</p><h1>Jornada {String(data.roundNumber).padStart(2,"0")}</h1><span>{data.league}</span></div><div className={styles.status}><i/><span>{data.stateLabel}</span></div></header>
  <nav className={styles.roundNav} aria-label="Cambiar jornada">{data.rounds.slice(0,6).map(round=><Link className={round===data.roundNumber?styles.selected:""} href={`/app/jornada?round=${round}`} key={round} aria-current={round===data.roundNumber?"page":undefined}>J{String(round).padStart(2,"0")}</Link>)}</nav>
  <section className={styles.scoreboard} aria-labelledby="team-score"><div className={styles.scoreCopy}><p>Tu equipo</p><div><strong id="team-score">{data.totalPoints===null?"—":number.format(Number(data.totalPoints))}</strong><span>puntos</span></div><small>{data.state==="FINAL"?`Resultado definitivo · revisión ${data.revision}`:data.state==="LIVE"?`${scored}/5 titulares finalizados`:data.state==="PROVISIONAL"?"Esperando los últimos cálculos":"La puntuación empezará con el primer partido"}</small></div><div className={styles.watermark} aria-hidden="true">{String(data.roundNumber).padStart(2,"0")}</div></section>
  <section className={styles.lineup} aria-labelledby="lineup-title"><div className={styles.sectionHead}><div><p>Quinteto titular</p><h2 id="lineup-title">Jugador a jugador</h2></div><span>{scored}/5 completados</span></div>{data.players.length?data.players.map((player,index)=><details className={styles.player} key={player.id} style={{"--delay":`${index*55}ms`} as React.CSSProperties}><summary><b>{String(index+1).padStart(2,"0")}</b><div><strong>{player.name}</strong><small data-player-state={player.state}><i/>{player.stateLabel}</small></div><span>{player.fantasyPoints===null?"—":number.format(Number(player.fantasyPoints))}<small> FP</small></span><em aria-hidden="true">⌄</em></summary><div className={styles.stats}><div><span>PTS</span><strong>{player.points}</strong></div><div><span>AST</span><strong>{player.assists}</strong></div><div><span>ROB</span><strong>{player.steals}</strong></div><p>{player.state==="DNP"?"No disputó el partido y aporta 0 puntos fantasy.":player.state==="PENDING"?"El partido terminó; la puntuación está pendiente de cálculo.":"Estadísticas sincronizadas del partido de esta jornada."}</p></div></details>):<div className={styles.noLineup}><strong>Sin alineación congelada</strong><p>Elige tus cinco titulares antes del cierre para aparecer aquí.</p><Link href="/app/mi-equipo">Ir a mi equipo →</Link></div>}</section>
  <ScoreChart values={data.cumulative}/>
 </main>}
