"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { LeagueDetailActions } from "./league-detail";
import { LeagueActivityPanel, LeagueMembersPanel } from "./social-league-panels";
import styles from "./league-hub.module.css";
type Member={id:string;role:string;userProfile:{authUserId:string;username:string|null;displayName:string|null}};
type League={id:string;competitionSeasonId:string;name:string;leagueCode:string;memberLimit:number;competitionSeason:{competition:{name:string}};memberships:Member[];currentRound:number|null};
type Ranking={fantasyTeamId:string;username:string|null;displayName:string|null;isMe:boolean;totalPoints:string;position:number|null;variation:number|null;round:{status:string;points:string|null}|null};
const manager=(row:{username:string|null;displayName:string|null})=>row.username?`@${row.username}`:row.displayName??"Manager";
export function LeagueHub({initialLeagues,authUserId,initialLeagueId}:{initialLeagues:League[];authUserId:string;initialLeagueId?:string}){
 const [leagues]=useState(initialLeagues),[selectedId,setSelectedId]=useState(initialLeagueId??initialLeagues[0]?.id??""),[tab,setTab]=useState<"ranking"|"activity"|"members">("ranking"),[ranking,setRanking]=useState<Ranking[]>([]),[rankState,setRankState]=useState("loading"),[switching,setSwitching]=useState(false),[message,setMessage]=useState("");const league=useMemo(()=>leagues.find(x=>x.id===selectedId)??leagues[0],[leagues,selectedId]);
 useEffect(()=>{if(!league)return;const controller=new AbortController();setRankState("loading");fetch(`/api/fantasy/rankings?competitionSeasonId=${league.competitionSeasonId}&leagueId=${league.id}`,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();setRanking(((await r.json()) as {data:Ranking[]}).data);setRankState("ready")}).catch(()=>{if(!controller.signal.aborted)setRankState("error")});return()=>controller.abort()},[league]);
 async function switchLeague(leagueId:string){setSwitching(true);setMessage("");const response=await fetch("/api/fantasy/leagues/active",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({leagueId})});setSwitching(false);if(response.ok){setSelectedId(leagueId);setTab("ranking")}else setMessage("No se pudo cambiar la liga activa.")}
 if(!league)return <main className={`${styles.page} ${styles.onboarding}`}><header><p>Liga privada</p><h1>Aún no tienes una liga</h1><span>Gestiona tus espacios de juego desde tu perfil.</span></header><Link className="primary-action" href="/app/perfil/ligas">Ir a Mis ligas →</Link></main>;
 const mine=league.memberships.find(m=>m.userProfile.authUserId===authUserId);return <main className={styles.page}><header className={styles.header}><div className={styles.leagueIdentity}><p>{league.competitionSeason.competition.name}</p>{leagues.length>1?<select aria-label="Cambiar de liga activa" value={league.id} disabled={switching} onChange={e=>void switchLeague(e.target.value)}>{leagues.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select>:<h1>{league.name}</h1>}</div><div className={styles.memberAction}><span>{league.memberships.length} de {league.memberLimit} managers</span><button onClick={()=>setTab("members")}>Ver miembros →</button></div></header>{message&&<p role="alert">{message}</p>}<nav className={styles.tabs} aria-label="Secciones de liga">{([['ranking','Clasificación'],['activity','Actividad'],['members','Miembros']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className={styles.view}>{tab==="ranking"&&(rankState==="loading"?<section className={styles.leagueStart} aria-busy="true"><h2>Actualizando posiciones…</h2></section>:rankState==="error"?<section className={styles.leagueStart}><h2>No se pudo actualizar</h2></section>:ranking.length?<section className={styles.ranking}><div className={styles.sectionHead}><div><p>Clasificación</p><h2>La carrera por el título</h2></div></div>{ranking.map(row=><div className={styles.rankRow} data-me={row.isMe} key={row.fantasyTeamId}><b>{row.position??"—"}</b><div><strong>{manager(row)}</strong><small>{row.round?.status==="PROVISIONAL"?"Jornada provisional":row.variation===0?"Sin cambios":row.variation?`${row.variation>0?"↑":"↓"} ${Math.abs(row.variation)}`:"Sin comparación"}</small></div><span>{Number(row.totalPoints).toFixed(1)} pts</span></div>)}</section>:<section className={styles.leagueStart}><h2>La clasificación espera resultados publicados</h2></section>)}{tab==="activity"&&<LeagueActivityPanel leagueId={league.id}/>} {tab==="members"&&<><LeagueMembersPanel leagueId={league.id}/><LeagueDetailActions leagueId={league.id} leagueCode={league.leagueCode} isOwner={mine?.role==="OWNER"}/></>}</div></main>;
}
