"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./home-dashboard.module.css";
type LeagueOption = { id: string; name: string };
export function LeagueSwitcher({ activeLeague, leagues }: { activeLeague: LeagueOption; leagues: LeagueOption[] }) {
  const router=useRouter(),rootRef=useRef<HTMLDivElement>(null),triggerRef=useRef<HTMLButtonElement>(null),optionRefs=useRef<Array<HTMLButtonElement|null>>([]),requestId=useRef(0),busy=useRef(false);
  const [success,setSuccess]=useState("");
  const [open,setOpen]=useState(false),[pending,setPending]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
  const close=(restoreFocus=true)=>{setOpen(false);if(restoreFocus)queueMicrotask(()=>triggerRef.current?.focus())};
  useEffect(()=>{if(!open)return;queueMicrotask(()=>optionRefs.current[leagues.findIndex((league)=>league.id===activeLeague.id)]?.focus());const outside=(event:PointerEvent)=>{if(!rootRef.current?.contains(event.target as Node))close()};const keyboard=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();close()}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",keyboard);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",keyboard)}},[activeLeague.id,leagues,open]);
  useEffect(()=>{busy.current=false;setPending(null);try{if(sessionStorage.getItem("canastio-league-switch")===activeLeague.id){sessionStorage.removeItem("canastio-league-switch");setSuccess(`Ahora estás en ${activeLeague.name}`);queueMicrotask(()=>triggerRef.current?.focus())}}catch{/* Storage is optional; context still comes from the server. */}},[activeLeague.id,activeLeague.name]);
  useEffect(()=>()=>{requestId.current++},[]);
  useEffect(()=>{const refresh=()=>router.refresh();window.addEventListener("focus",refresh);return()=>window.removeEventListener("focus",refresh)},[router]);
  async function selectLeague(leagueId:string){if(busy.current)return;if(leagueId===activeLeague.id){close();return}busy.current=true;let confirmed=false;const current=++requestId.current;setPending(leagueId);setError(null);try{const response=await fetch("/api/fantasy/leagues/active",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({leagueId})});const result=await response.json().catch(()=>null) as {data?:{activeLeagueId?:string};error?:{code?:string}}|null;if(current!==requestId.current)return;if(!response.ok||result?.data?.activeLeagueId!==leagueId){if(response.status===401){router.refresh();return}if(response.status===404||result?.error?.code==="LEAGUE_NOT_FOUND"){setError("Esta liga ya no está disponible. Hemos actualizado tu selección.");close(false);router.refresh();return}throw new Error("ACTIVE_LEAGUE_UPDATE_FAILED")}confirmed=true;close();try{sessionStorage.setItem("canastio-league-switch",leagueId)}catch{/* Optional announcement persistence. */}router.refresh()}catch{if(current===requestId.current){setError("No se pudo confirmar el cambio de liga. Estamos actualizando tu selección.");router.refresh()}}finally{if(current===requestId.current&&!confirmed){busy.current=false;setPending(null)}}}
  const move=(index:number,direction:1|-1)=>optionRefs.current[(index+direction+leagues.length)%leagues.length]?.focus();
  return <div className={styles.leagueSwitcher} ref={rootRef}><button ref={triggerRef} type="button" className={styles.leagueTrigger} aria-haspopup="menu" aria-expanded={open} onClick={()=>{setOpen(value=>!value);setError(null)}} onKeyDown={(event)=>{if(!open&&(event.key==="ArrowDown"||event.key==="ArrowUp")){event.preventDefault();setOpen(true)}}}><span>{activeLeague.name}</span><svg className={styles.chevron} viewBox="0 0 16 16" width="14" height="14" fill="none" aria-hidden="true"><path d="m4 6 4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg></button>{open?<div className={styles.leagueMenu} role="menu" aria-label="Cambiar de liga"><p>Cambiar de liga</p>{leagues.map((league,index)=><button ref={(node)=>{optionRefs.current[index]=node}} key={league.id} type="button" role="menuitemradio" aria-checked={league.id===activeLeague.id} disabled={pending!==null} onClick={()=>void selectLeague(league.id)} onKeyDown={(event)=>{if(event.key==="ArrowDown"){event.preventDefault();move(index,1)}if(event.key==="ArrowUp"){event.preventDefault();move(index,-1)}}}><span>{league.name}</span><span aria-hidden="true">{pending===league.id?"…":league.id===activeLeague.id?"✓":""}</span></button>)}<Link href="/app/perfil/ligas" role="menuitem" onClick={()=>close(false)}>Gestionar mis ligas</Link></div>:null}{success?<p role="status">{success}</p>:null}{error?<p className={styles.leagueError} role="alert">{error}</p>:null}</div>
}
