"use client";

import { useMemo, useState } from "react";
import { LeagueDetailActions } from "./league-detail";
import styles from "./league-hub.module.css";

type Member={id:string;role:string;userProfile:{authUserId:string;displayName:string|null}};
type League={id:string;name:string;leagueCode:string;version:number;memberLimit:number;competitionSeason:{competition:{name:string}};memberships:Member[];currentRound:number|null;rules:{budgetCredits:number;rosterSize:number;starterCount:number;substituteCount:number;maxPerRealTeam:number}|null};
type Tab="ranking"|"activity"|"league";
const money=(value:number)=>new Intl.NumberFormat("es-ES",{maximumFractionDigits:0}).format(value);
async function responseBody(response:Response){const type=response.headers.get("content-type")??"";if(!type.includes("application/json"))return null;return response.json() as Promise<{data?:League;error?:{code?:string}}>}

export function LeagueHub({initialLeagues,seasons,authUserId,initialLeagueId}:{initialLeagues:League[];seasons:{id:string;label:string}[];authUserId:string;initialLeagueId?:string}){
  const [leagues,setLeagues]=useState(initialLeagues);
  const [selectedId,setSelectedId]=useState(initialLeagues.some(l=>l.id===initialLeagueId)?initialLeagueId!:initialLeagues[0]?.id??"");
  const [tab,setTab]=useState<Tab>("ranking");
  const [name,setName]=useState(""); const [seasonId,setSeasonId]=useState(seasons[0]?.id??""); const [createPassword,setCreatePassword]=useState("");const [code,setCode]=useState("");const [joinPassword,setJoinPassword]=useState(""); const [message,setMessage]=useState("");
  const league=useMemo(()=>leagues.find(item=>item.id===selectedId)??leagues[0],[leagues,selectedId]);
  async function create(){const r=await fetch("/api/fantasy/leagues",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,competitionSeasonId:seasonId,password:createPassword})});const b=await responseBody(r);if(!r.ok)return setMessage(b?.error?.code??"No se pudo crear");location.reload();}
  async function join(){const r=await fetch("/api/fantasy/leagues/join",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,password:joinPassword})});const b=await responseBody(r);if(!r.ok||!b?.data)return setMessage(b?.error?.code??"Código o contraseña incorrectos");setLeagues([...leagues,b.data]);location.reload();}
  if(!league)return <main className={`${styles.page} ${styles.onboarding}`}><header><p>Liga privada</p><h1>Juega con los tuyos</h1><span>Crea una liga o entra con su código y contraseña.</span></header><section className={styles.actions}><div><span className={styles.step}>01</span><h2>Crear una liga</h2><input aria-label="Nombre de la liga" placeholder="Nombre de la liga" value={name} onChange={e=>setName(e.target.value)}/><select aria-label="Competición" value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select><input aria-label="Contraseña de la nueva liga" type="password" autoComplete="new-password" minLength={6} maxLength={72} placeholder="Contraseña · mínimo 6 caracteres" value={createPassword} onChange={e=>setCreatePassword(e.target.value)}/><button disabled={name.trim().length<3||!seasonId||createPassword.length<6} onClick={()=>void create()}>Crear liga <span>→</span></button></div><div><span className={styles.step}>02</span><h2>Unirme a una liga</h2><input aria-label="Código de liga" autoCapitalize="characters" placeholder="CNST-XXXXXX" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><input aria-label="Contraseña de liga" type="password" autoComplete="current-password" placeholder="Contraseña" value={joinPassword} onChange={e=>setJoinPassword(e.target.value)}/><button disabled={!code.trim()||!joinPassword} onClick={()=>void join()}>Entrar <span>→</span></button></div></section>{message&&<p role="alert" className={styles.message}>{message}</p>}</main>;
  const mine=league.memberships.find(m=>m.userProfile.authUserId===authUserId);
  const round=league.currentRound?`Jornada ${league.currentRound}`:"Jornada pendiente";
  return <main className={styles.page}>
    <header className={styles.header}><div><p>{league.competitionSeason.competition.name}</p>{leagues.length>1?<select aria-label="Cambiar de liga" value={league.id} onChange={e=>setSelectedId(e.target.value)}>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>:<h1>{league.name}</h1>}</div><span className={styles.members}><i/> {league.memberships.length}/{league.memberLimit} managers</span></header>
    <section className={styles.summary} aria-label="Resumen de liga"><div><span>Temporada</span><strong>{round}</strong></div><div><span>Líder</span><strong>Por decidir</strong></div><div className={styles.myPosition}><span>Tu posición</span><strong>—</strong><small>Se activa tras la primera jornada</small></div></section>
    <nav className={styles.tabs} aria-label="Secciones de liga">{([["ranking","Clasificación"],["activity","Actividad"],["league","Mi liga"]] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    <div className={styles.view} key={tab}>
      {tab==="ranking"&&<><section className={styles.round}><div><p>Estado de la jornada</p><h2>{round}</h2><span>La clasificación semanal aparecerá al cerrar y calcular la jornada.</span></div><strong aria-hidden="true">{league.currentRound??"—"}</strong></section><section className={styles.ranking}><div className={styles.sectionHead}><div><p>Clasificación general</p><h2>La carrera por el título</h2></div><span>{league.memberships.length} managers</span></div>{league.memberships.map((member,index)=><div className={styles.rankRow} key={member.id}><b>{String(index+1).padStart(2,"0")}</b><div><strong>{member.userProfile.displayName??"Manager Canastio"}{member.userProfile.authUserId===authUserId&&<em>Tú</em>}</strong><small>{member.role==="OWNER"?"Administrador":"Manager"}</small></div><span>— pts</span><i>pendiente</i></div>)}</section></>}
      {tab==="activity"&&<section className={styles.emptyView}><span aria-hidden="true">↗</span><p>Actividad de la liga</p><h2>Aquí se cuenta lo que pasa</h2><div className={styles.newsPreview}><time>Próximamente</time><strong>Fichajes, cambios de valor y clausulazos aparecerán como noticias.</strong></div></section>}
      {tab==="league"&&<><section className={styles.settings}><div className={styles.sectionHead}><div><p>Configuración</p><h2>Reglas de {league.name}</h2></div><span>{mine?.role==="OWNER"?"Administrador":"Solo lectura"}</span></div><dl><div><dt>Código de liga</dt><dd>{league.leagueCode}</dd></div><div><dt>Competición</dt><dd>{league.competitionSeason.competition.name}</dd></div><div><dt>Presupuesto inicial</dt><dd>{league.rules?`${money(league.rules.budgetCredits)} créditos`:"Pendiente"}</dd></div><div><dt>Plantilla</dt><dd>{league.rules?`${league.rules.rosterSize} jugadores · ${league.rules.starterCount} titulares · ${league.rules.substituteCount} suplentes`:"Pendiente"}</dd></div><div><dt>Límite por equipo real</dt><dd>{league.rules?league.rules.maxPerRealTeam:"Pendiente"}</dd></div></dl></section><section className={styles.managers}><div className={styles.sectionHead}><div><p>Vestuario</p><h2>Managers</h2></div><span>{league.memberships.length}/{league.memberLimit}</span></div>{league.memberships.map(member=><div key={member.id}><strong>{member.userProfile.displayName??"Manager Canastio"}</strong><span>{member.role==="OWNER"?"Administrador":"Miembro"}</span></div>)}<LeagueDetailActions leagueId={league.id} leagueCode={league.leagueCode} isOwner={mine?.role==="OWNER"}/></section></>}
    </div>
  </main>;
}
