import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({preference:vi.fn(),membership:vi.fn(),subscriptions:vi.fn(),freshSubscription:vi.fn(),createDelivery:vi.fn(),findDelivery:vi.fn(),claim:vi.fn(),updateDelivery:vi.fn(),revoke:vi.fn()}));
vi.mock("./db",()=>({db:{notificationPreference:{findUnique:mocks.preference},pushSubscription:{findMany:mocks.subscriptions,findFirst:mocks.freshSubscription,updateMany:mocks.revoke},leagueMembership:{findFirst:mocks.membership},notificationDelivery:{create:mocks.createDelivery,findUnique:mocks.findDelivery,updateMany:mocks.updateDelivery}}}));
import { dispatchNotification } from "./notifications";
const now=new Date("2026-09-15T10:00:00Z"),clock=()=>now;
const subscription={id:"s1",userProfileId:"u1",endpoint:"https://push.test/1",p256dh:"p",auth:"a",vapidKeyVersion:"v1"};
const event={userProfileId:"00000000-0000-0000-0000-000000000001",intent:"ROUND_RESULT" as const,eventKey:"round:4:revision:1",title:"Jornada calculada",body:"Ya puedes consultar tus puntos",destination:"/app/jornada"};
describe("notification dispatcher",()=>{
 beforeEach(()=>{vi.clearAllMocks();process.env.VAPID_KEY_VERSION="v1";mocks.preference.mockResolvedValue({enabled:true});mocks.subscriptions.mockResolvedValue([subscription]);mocks.freshSubscription.mockResolvedValue(subscription);mocks.createDelivery.mockResolvedValue({id:"d1"});mocks.findDelivery.mockResolvedValue({attemptCount:0});mocks.updateDelivery.mockResolvedValue({count:1});mocks.revoke.mockResolvedValue({count:1})});
 it("does not create deliveries when preference is disabled",async()=>{mocks.preference.mockResolvedValue({enabled:false});const send=vi.fn();expect(await dispatchNotification(event,send,clock)).toEqual({delivered:0,skipped:true});expect(send).not.toHaveBeenCalled()});
 it("does not disclose a league event to a non-member",async()=>{mocks.membership.mockResolvedValue(null);const send=vi.fn();expect(await dispatchNotification({...event,leagueId:"league-2"},send,clock)).toEqual({delivered:0,skipped:true});expect(send).not.toHaveBeenCalled()});
 it("claims once and sends a minimal safe payload",async()=>{const send=vi.fn().mockResolvedValue(undefined);expect(await dispatchNotification(event,send,clock)).toEqual({delivered:1,skipped:false});expect(JSON.parse(send.mock.calls[0][1])).toEqual(expect.objectContaining({destination:"/app/jornada"}));expect(send.mock.calls[0][1]).not.toContain(subscription.endpoint)});
 it("does not double-send a live concurrent claim",async()=>{mocks.createDelivery.mockRejectedValue({code:"P2002"});mocks.findDelivery.mockResolvedValue({id:"d1",status:"PENDING",attemptCount:0,nextAttemptAt:now,claimedAt:now});const send=vi.fn();await dispatchNotification(event,send,clock);expect(send).not.toHaveBeenCalled()});
 it("allows at most one sender across two concurrent dispatchers",async()=>{let created=false;mocks.createDelivery.mockImplementation(async()=>{if(created)throw{code:"P2002"};created=true;return{id:"d1"}});mocks.findDelivery.mockResolvedValue({id:"d1",status:"PENDING",attemptCount:0,nextAttemptAt:now,claimedAt:now});const send=vi.fn().mockResolvedValue(undefined);await Promise.all([dispatchNotification(event,send,clock),dispatchNotification(event,send,clock)]);expect(send).toHaveBeenCalledTimes(1)});
 it("recovers an abandoned claim after five minutes",async()=>{mocks.createDelivery.mockRejectedValue({code:"P2002"});mocks.findDelivery.mockResolvedValueOnce({id:"d1",status:"PENDING",attemptCount:0,nextAttemptAt:now,claimedAt:new Date(now.getTime()-300001)}).mockResolvedValue({attemptCount:0});await dispatchNotification(event,vi.fn().mockResolvedValue(undefined),clock);expect(mocks.updateDelivery).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({claimToken:expect.any(String)})}))});
 it("revokes only a subscription rejected as gone",async()=>{const error=Object.assign(new Error("secret provider detail"),{statusCode:410});await dispatchNotification(event,vi.fn().mockRejectedValue(error),clock);expect(mocks.revoke).toHaveBeenCalledWith({where:{id:"s1",userProfileId:event.userProfileId},data:{revokedAt:now,revokedReason:"EXPIRED"}});expect(mocks.updateDelivery).toHaveBeenLastCalledWith(expect.objectContaining({data:expect.objectContaining({status:"EXPIRED",lastErrorCode:"HTTP_410"})}))});
 it("persists controlled backoff and stops after three attempts",async()=>{mocks.createDelivery.mockRejectedValue({code:"P2002"});mocks.findDelivery.mockResolvedValueOnce({id:"d1",status:"RETRYABLE",attemptCount:2,nextAttemptAt:now,claimedAt:null}).mockResolvedValue({attemptCount:2});await dispatchNotification(event,vi.fn().mockRejectedValue(new Error("token=private")),clock);expect(mocks.updateDelivery).toHaveBeenLastCalledWith(expect.objectContaining({data:expect.objectContaining({status:"FAILED",lastErrorCode:"SEND_FAILED",attemptCount:{increment:1}})}))});
});
