import { Prisma } from "@prisma/client";
import { INVITE_TTL_MS, MAX_LEAGUE_MEMBERS, createInviteToken, hashInviteToken, validLeagueName, type LeagueErrorCode } from "../../../../packages/domain/private-league";
import { db } from "./db";

export type LeagueActor = { authUserId: string };
export class LeagueServiceError extends Error { constructor(public code: LeagueErrorCode, public status = 409) { super(code); } }
function fail(code: LeagueErrorCode, status = 409): never { throw new LeagueServiceError(code, status); }
const enabled = () => process.env.FANTASY_LEAGUE_MUTATIONS_ENABLED !== "false";
async function profileId(client: Prisma.TransactionClient | typeof db, actor: LeagueActor) { const p = await client.userProfile.findUnique({ where: { authUserId: actor.authUserId }, select: { id: true } }); if (!p) fail("LEAGUE_NOT_FOUND", 404); return p.id; }

export async function listLeagues(actor: LeagueActor) { const userProfileId = await profileId(db, actor); return db.fantasyLeague.findMany({ where: { memberships: { some: { userProfileId, status: "ACTIVE" } }, status: "ACTIVE" }, include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" }, include: { userProfile: true } } }, orderBy: { updatedAt: "desc" } }); }
export async function getLeague(actor: LeagueActor, leagueId: string) { const userProfileId = await profileId(db, actor); const league = await db.fantasyLeague.findFirst({ where: { id: leagueId, status: "ACTIVE", memberships: { some: { userProfileId, status: "ACTIVE" } } }, include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" }, include: { userProfile: true }, orderBy: { joinedAt: "asc" } } } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); return league; }
export async function createLeague(actor: LeagueActor, input: { name: string; competitionSeasonId: string }) { if (!enabled()) fail("FEATURE_DISABLED"); const name = validLeagueName(input.name); return db.$transaction(async tx => { const ownerProfileId = await profileId(tx, actor); const league = await tx.fantasyLeague.create({ data: { name, competitionSeasonId: input.competitionSeasonId, ownerProfileId, memberLimit: MAX_LEAGUE_MEMBERS } }); await tx.leagueMembership.create({ data: { leagueId: league.id, userProfileId: ownerProfileId, role: "OWNER" } }); return league; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
export async function createInvite(actor: LeagueActor, leagueId: string) { if (!enabled()) fail("FEATURE_DISABLED"); const token = createInviteToken(); await db.$transaction(async tx => { const owner = await profileId(tx, actor); const league = await tx.fantasyLeague.findFirst({ where: { id: leagueId, ownerProfileId: owner, status: "ACTIVE" } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); await tx.leagueInvite.updateMany({ where: { leagueId, status: "ACTIVE" }, data: { status: "REVOKED", revokedAt: new Date() } }); await tx.leagueInvite.create({ data: { leagueId, tokenHash: hashInviteToken(token), expiresAt: new Date(Date.now() + INVITE_TTL_MS) } }); }); return { token, expiresAt: new Date(Date.now() + INVITE_TTL_MS).toISOString() }; }
export async function invitePreview(token: string) { let hash: string; try { hash = hashInviteToken(token); } catch { return fail("INVITE_INVALID", 404); } const invite = await db.leagueInvite.findUnique({ where: { tokenHash: hash }, include: { league: { include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" } } } } } }); if (!invite) fail("INVITE_INVALID", 404); if (invite.status === "REVOKED") fail("INVITE_REVOKED"); if (invite.expiresAt <= new Date()) fail("INVITE_EXPIRED"); return { name: invite.league.name, competition: invite.league.competitionSeason.competition.name, members: invite.league.memberships.length, limit: invite.league.memberLimit }; }
export async function joinLeague(actor: LeagueActor, token: string) { if (!enabled()) fail("FEATURE_DISABLED"); return db.$transaction(async tx => { const userProfileId = await profileId(tx, actor); const hash = hashInviteToken(token); const invite = await tx.leagueInvite.findUnique({ where: { tokenHash: hash }, include: { league: true } }); if (!invite) fail("INVITE_INVALID", 404); await tx.$queryRaw(Prisma.sql`SELECT id FROM fantasy_leagues WHERE id=${invite.leagueId}::uuid FOR UPDATE`); if (invite.status !== "ACTIVE") fail("INVITE_REVOKED"); if (invite.expiresAt <= new Date()) fail("INVITE_EXPIRED"); const existing = await tx.leagueMembership.findUnique({ where: { leagueId_userProfileId: { leagueId: invite.leagueId, userProfileId } } }); if (existing?.status === "ACTIVE") fail("ALREADY_MEMBER"); const count = await tx.leagueMembership.count({ where: { leagueId: invite.leagueId, status: "ACTIVE" } }); if (count >= invite.league.memberLimit) fail("LEAGUE_FULL"); await tx.leagueMembership.upsert({ where: { leagueId_userProfileId: { leagueId: invite.leagueId, userProfileId } }, create: { leagueId: invite.leagueId, userProfileId }, update: { status: "ACTIVE", role: "MEMBER", leftAt: null, joinedAt: new Date() } }); return invite.league; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
export async function leaveLeague(actor: LeagueActor, leagueId: string) { if (!enabled()) fail("FEATURE_DISABLED"); return db.$transaction(async tx => { const userProfileId = await profileId(tx, actor); const member = await tx.leagueMembership.findUnique({ where: { leagueId_userProfileId: { leagueId, userProfileId } } }); if (!member || member.status !== "ACTIVE") fail("LEAGUE_NOT_FOUND", 404); if (member.role === "OWNER") fail("OWNER_CANNOT_LEAVE"); return tx.leagueMembership.update({ where: { id: member.id }, data: { status: "LEFT", leftAt: new Date() } }); }); }
export async function deleteLeague(actor: LeagueActor, leagueId: string, input: { expectedVersion: number; confirmation: string }) { if (!enabled()) fail("FEATURE_DISABLED"); return db.$transaction(async tx => { const ownerProfileId = await profileId(tx, actor); const league = await tx.fantasyLeague.findFirst({ where: { id: leagueId, ownerProfileId, status: "ACTIVE" }, include: { memberships: { where: { status: "ACTIVE" } } } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); if (league.version !== input.expectedVersion) fail("VERSION_CONFLICT"); if (league.memberships.length > 1 && input.confirmation !== league.name) fail("CONFIRMATION_REQUIRED"); await tx.leagueInvite.updateMany({ where: { leagueId, status: "ACTIVE" }, data: { status: "REVOKED", revokedAt: new Date() } }); return tx.fantasyLeague.update({ where: { id: leagueId, version: input.expectedVersion }, data: { status: "ARCHIVED", version: { increment: 1 } } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
