import { Prisma } from "@prisma/client";
import { INVITE_TTL_MS, MAX_LEAGUE_MEMBERS, createInviteToken, createLeagueCode, hashInviteToken, hashLeaguePassword, normalizeLeagueCode, validLeagueName, validLeaguePassword, verifyLeaguePassword, type LeagueErrorCode } from "../../../../packages/domain/private-league";
import { db } from "./db";
import { enqueuePushEvent, wakePushWorker } from "./push-outbox";

export type LeagueActor = { authUserId: string };
export class LeagueServiceError extends Error { constructor(public code: LeagueErrorCode, public status = 409) { super(code); } }
function fail(code: LeagueErrorCode, status = 409): never { throw new LeagueServiceError(code, status); }
const enabled = () => process.env.FANTASY_LEAGUE_MUTATIONS_ENABLED !== "false";
async function profileId(client: Prisma.TransactionClient | typeof db, actor: LeagueActor, requireComplete = false) { const p = await client.userProfile.findUnique({ where: { authUserId: actor.authUserId }, select: { id: true, username: true } }); if (!p) fail("LEAGUE_NOT_FOUND", 404); if (requireComplete && !p.username) fail("INVALID_INPUT", 422); return p.id; }

export async function listLeagues(actor: LeagueActor) { const userProfileId = await profileId(db, actor); return db.fantasyLeague.findMany({ where: { memberships: { some: { userProfileId, status: "ACTIVE" } }, status: "ACTIVE", legacyTeamId: null }, omit:{passwordHash:true},include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" }, include: { userProfile: true } } }, orderBy: { updatedAt: "desc" } }); }
export async function getLeague(actor: LeagueActor, leagueId: string) { const userProfileId = await profileId(db, actor); const league = await db.fantasyLeague.findFirst({ where: { id: leagueId, status: "ACTIVE", memberships: { some: { userProfileId, status: "ACTIVE" } } },omit:{passwordHash:true}, include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" }, include: { userProfile: true }, orderBy: { joinedAt: "asc" } } } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); return league; }
export async function createLeague(actor: LeagueActor, input: { name: string; competitionSeasonId: string; password:string }) { if (!enabled()) fail("FEATURE_DISABLED"); const name = validLeagueName(input.name);const passwordHash=await hashLeaguePassword(validLeaguePassword(input.password)); return db.$transaction(async tx => { const ownerProfileId = await profileId(tx, actor, true);let leagueCode=createLeagueCode();for(let attempt=0;attempt<5;attempt++){if(!await tx.fantasyLeague.findUnique({where:{leagueCode}}))break;leagueCode=createLeagueCode()} const league = await tx.fantasyLeague.create({ data: { name, competitionSeasonId: input.competitionSeasonId, ownerProfileId, memberLimit: MAX_LEAGUE_MEMBERS,leagueCode,passwordHash },omit:{passwordHash:true} }); await tx.leagueMembership.create({ data: { leagueId: league.id, userProfileId: ownerProfileId, role: "OWNER" } }); await enqueuePushEvent(tx,{userProfileId:ownerProfileId,leagueId:league.id,intent:"LEAGUE_ACTIVITY",eventKey:`league:${league.id}:created`,title:"Liga creada",body:"Tu nueva liga ya está disponible.",destination:`/app/ligas/${league.id}`}); return league; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }).then(result=>{void wakePushWorker();return result;}); }
export async function createInvite(actor: LeagueActor, leagueId: string) { if (!enabled()) fail("FEATURE_DISABLED"); const token = createInviteToken(); await db.$transaction(async tx => { const owner = await profileId(tx, actor, true); const league = await tx.fantasyLeague.findFirst({ where: { id: leagueId, ownerProfileId: owner, status: "ACTIVE" } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); await tx.leagueInvite.updateMany({ where: { leagueId, status: "ACTIVE" }, data: { status: "REVOKED", revokedAt: new Date() } }); await tx.leagueInvite.create({ data: { leagueId, tokenHash: hashInviteToken(token), expiresAt: new Date(Date.now() + INVITE_TTL_MS) } }); }); return { token, expiresAt: new Date(Date.now() + INVITE_TTL_MS).toISOString() }; }
export async function invitePreview(token: string) { let hash: string; try { hash = hashInviteToken(token); } catch { return fail("INVITE_INVALID", 404); } const invite = await db.leagueInvite.findUnique({ where: { tokenHash: hash }, include: { league: { include: { competitionSeason: { include: { competition: true } }, memberships: { where: { status: "ACTIVE" } } } } } }); if (!invite) fail("INVITE_INVALID", 404); if (invite.status === "REVOKED") fail("INVITE_REVOKED"); if (invite.expiresAt <= new Date()) fail("INVITE_EXPIRED"); return { name: invite.league.name, competition: invite.league.competitionSeason.competition.name, members: invite.league.memberships.length, limit: invite.league.memberLimit }; }
export async function joinLeague(actor: LeagueActor, input:{code:string;password:string}) { if (!enabled()) fail("FEATURE_DISABLED");let code:string;try{code=normalizeLeagueCode(input.code)}catch{fail("INVALID_CREDENTIALS",401)}const candidate=await db.fantasyLeague.findUnique({where:{leagueCode:code},select:{id:true,passwordHash:true}});if(!candidate?.passwordHash||!await verifyLeaguePassword(input.password,candidate.passwordHash))fail("INVALID_CREDENTIALS",401); return db.$transaction(async tx => { const userProfileId = await profileId(tx, actor, true);await tx.$queryRaw(Prisma.sql`SELECT id FROM fantasy_leagues WHERE id=${candidate.id}::uuid FOR UPDATE`);const league=await tx.fantasyLeague.findUnique({where:{id:candidate.id},omit:{passwordHash:true}});if(!league||league.status!=="ACTIVE")fail("LEAGUE_NOT_FOUND",404); const existing = await tx.leagueMembership.findUnique({ where: { leagueId_userProfileId: { leagueId: league.id, userProfileId } } }); if (existing?.status === "ACTIVE") fail("ALREADY_MEMBER"); const count = await tx.leagueMembership.count({ where: { leagueId: league.id, status: "ACTIVE" } }); if (count >= league.memberLimit) fail("LEAGUE_FULL"); await tx.leagueMembership.upsert({ where: { leagueId_userProfileId: { leagueId: league.id, userProfileId } }, create: { leagueId: league.id, userProfileId }, update: { status: "ACTIVE", role: "MEMBER", leftAt: null, joinedAt: new Date() } }); await enqueuePushEvent(tx,{userProfileId,leagueId:league.id,intent:"LEAGUE_ACTIVITY",eventKey:`league:${league.id}:member:${userProfileId}:joined`,title:"Te has unido a la liga",body:"Ya puedes participar en la liga.",destination:`/app/ligas/${league.id}`}); return league; }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }).then(result=>{void wakePushWorker();return result;}); }
export async function updateLeaguePassword(actor:LeagueActor,leagueId:string,password:string){if(!enabled())fail("FEATURE_DISABLED");const passwordHash=await hashLeaguePassword(validLeaguePassword(password));const ownerProfileId=await profileId(db,actor,true);const result=await db.fantasyLeague.updateMany({where:{id:leagueId,ownerProfileId,status:"ACTIVE"},data:{passwordHash,version:{increment:1}}});if(!result.count)fail("LEAGUE_NOT_FOUND",404);return {updated:true};}
export async function leaveLeague(actor: LeagueActor, leagueId: string) { if (!enabled()) fail("FEATURE_DISABLED"); return db.$transaction(async tx => { const userProfileId = await profileId(tx, actor, true); const member = await tx.leagueMembership.findUnique({ where: { leagueId_userProfileId: { leagueId, userProfileId } } }); if (!member || member.status !== "ACTIVE") fail("LEAGUE_NOT_FOUND", 404); if (member.role === "OWNER") fail("OWNER_CANNOT_LEAVE"); return tx.leagueMembership.update({ where: { id: member.id }, data: { status: "LEFT", leftAt: new Date() } }); }); }
export async function deleteLeague(actor: LeagueActor, leagueId: string, input: { expectedVersion: number; confirmation: string }) { if (!enabled()) fail("FEATURE_DISABLED"); return db.$transaction(async tx => { const ownerProfileId = await profileId(tx, actor, true); const league = await tx.fantasyLeague.findFirst({ where: { id: leagueId, ownerProfileId, status: "ACTIVE" }, include: { memberships: { where: { status: "ACTIVE" } } } }); if (!league) fail("LEAGUE_NOT_FOUND", 404); if (league.version !== input.expectedVersion) fail("VERSION_CONFLICT"); if (league.memberships.length > 1 && input.confirmation !== league.name) fail("CONFIRMATION_REQUIRED"); await tx.leagueInvite.updateMany({ where: { leagueId, status: "ACTIVE" }, data: { status: "REVOKED", revokedAt: new Date() } }); return tx.fantasyLeague.update({ where: { id: leagueId, version: input.expectedVersion }, data: { status: "ARCHIVED", version: { increment: 1 } } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
