"use client";
import { useEffect, useState } from "react";
import { NOTIFICATION_GROUPS, type NotificationIntent } from "../../../../../packages/domain/notifications";

type InstallPrompt = Event & { prompt(): Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
const LABELS: Record<NotificationIntent,string>={MARKET_PRICE:"Cambios importantes de precio",MARKET_OFFER:"Ofertas recibidas",MARKET_OUTBID:"Pujas superadas",MARKET_SOLD:"Jugador vendido",TEAM_INJURY:"Lesiones",TEAM_CUTOFF:"Aviso antes del cierre",TEAM_LINEUP:"Recordatorio de alineación",LEAGUE_CLAUSE:"Clausulazos",LEAGUE_ACTIVITY:"Actividad importante",LEAGUE_MESSAGE:"Mensajes",ROUND_START:"Comienzo de mis partidos",ROUND_RESULT:"Resultados"};
const decode=(value:string)=>{const pad="=".repeat((4-value.length%4)%4);return Uint8Array.from(atob((value+pad).replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0))};

export function PwaSettings({vapidPublicKey,section="all"}:{vapidPublicKey:string;section?:"all"|"install"|"notifications"}){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[standalone,setStandalone]=useState(false),[ios,setIos]=useState(false),[permission,setPermission]=useState<NotificationPermission|"unsupported">("unsupported"),[registered,setRegistered]=useState(false),[prefs,setPrefs]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const nav=navigator as Navigator&{standalone?:boolean};setStandalone(matchMedia("(display-mode: standalone)").matches||nav.standalone===true);setIos(/iphone|ipad|ipod/i.test(navigator.userAgent));setPermission("Notification" in window?Notification.permission:"unsupported");fetch("/api/notifications").then(r=>r.ok?r.json():null).then(r=>{if(r?.data?.preferences)setPrefs(r.data.preferences);setRegistered(Boolean(r?.data?.subscriptions?.length))}).catch(()=>setMessage("No pudimos cargar tus preferencias."));const capture=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);
 async function install(){if(!prompt)return;await prompt.prompt();await prompt.userChoice;setPrompt(null)}
 async function ensureSubscription(){if(!("serviceWorker" in navigator)||!("PushManager" in window)||!vapidPublicKey)return false;const result=await Notification.requestPermission();setPermission(result);if(result!=="granted")return false;const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();subscription??=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(vapidPublicKey)});const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(subscription.toJSON())});setRegistered(response.ok);return response.ok}
 async function enableDevice(){setBusy(true);setMessage("");try{if(!await ensureSubscription())setMessage(Notification.permission==="denied"?"El navegador ha bloqueado las notificaciones. Permítelas en los ajustes del sitio.":"Este dispositivo no ha podido registrarse para recibir avisos.");}catch{setMessage("No se pudo registrar este dispositivo. Comprueba los permisos y vuelve a intentarlo.")}finally{setBusy(false)}}
 async function toggle(intent:NotificationIntent){const next=!prefs[intent];setBusy(true);setMessage("");try{if(next&&!(await ensureSubscription())){setMessage(Notification.permission==="denied"?"Las notificaciones están bloqueadas en el navegador. Actívalas desde los permisos del sitio.":"No se pudo activar este dispositivo.");return}const response=await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({intent,enabled:next})});if(!response.ok)throw new Error();setPrefs(current=>({...current,[intent]:next}))}catch{setMessage("No pudimos guardar el cambio. Inténtalo de nuevo.")}finally{setBusy(false)}}
 const supported=permission!=="unsupported"&&Boolean(vapidPublicKey);
 return <>
  {section!=="notifications"&&!standalone&&(prompt||ios)?<section className="profile-group" aria-labelledby="install-title"><div className="profile-group-heading"><h2 id="install-title">{ios?"Añadir a pantalla de inicio":"Instalar Canastio"}</h2></div><div className="profile-list pwa-action"><div><strong>Acceso rápido desde tu dispositivo</strong><small>{ios?"En Safari, pulsa Compartir → Añadir a pantalla de inicio.":"Instala Canastio para abrirlo como una aplicación."}</small></div>{prompt?<button className="primary-action" onClick={install}>Instalar</button>:null}</div></section>:null}
  {section!=="install"?<section className="profile-group" aria-labelledby="notifications-title"><div className="device-status"><span><small>Estado del dispositivo</small><strong>{!supported?"No compatible":permission==="denied"?"Bloqueadas":registered?"Activadas":"Sin activar"}</strong></span>{supported&&permission!=="denied"&&!registered?<button className="primary-action" disabled={busy} onClick={()=>void enableDevice()}>Permitir notificaciones</button>:null}</div><p className="settings-help">El permiso del navegador y tus preferencias se gestionan por separado.</p>{permission==="denied"?<p className="settings-status">Bloqueadas en este dispositivo. Permítelas desde los ajustes del sitio.</p>:null}{message?<p className="form-message error" role="status">{message}</p>:null}
  {Object.entries(NOTIFICATION_GROUPS).map(([group,intents])=><div key={group} className="notification-group"><h3>{group}</h3><div className="profile-list">{intents.map(intent=><label className="notification-row" key={intent}><span>{LABELS[intent]}</span><input type="checkbox" role="switch" checked={Boolean(prefs[intent])&&permission!=="denied"} disabled={busy||!supported||permission==="denied"} onChange={()=>toggle(intent)}/></label>)}</div></div>)}</section>:null}
 </>
}
