"use client";
import { useEffect, useState } from "react";
import { NOTIFICATION_GROUPS, type NotificationIntent } from "../../../../../packages/domain/notifications";

type InstallPrompt = Event & { prompt(): Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
const LABELS: Record<NotificationIntent,string>={MARKET_PRICE:"Cambios importantes de precio",MARKET_OFFER:"Ofertas recibidas",MARKET_OUTBID:"Pujas superadas",MARKET_SOLD:"Jugador vendido",TEAM_INJURY:"Lesiones",TEAM_CUTOFF:"Proximidad del bloqueo",TEAM_LINEUP:"Recordatorio de alineación",LEAGUE_CLAUSE:"Clausulazos",LEAGUE_ACTIVITY:"Actividad importante",LEAGUE_MESSAGE:"Mensajes",ROUND_START:"Inicio de partidos",ROUND_RESULT:"Resultados"};
const decode=(value:string)=>{const pad="=".repeat((4-value.length%4)%4);return Uint8Array.from(atob((value+pad).replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0))};

export function PwaSettings({vapidPublicKey}:{vapidPublicKey:string}){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[standalone,setStandalone]=useState(false),[ios,setIos]=useState(false),[permission,setPermission]=useState<NotificationPermission|"unsupported">("unsupported"),[prefs,setPrefs]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const nav=navigator as Navigator&{standalone?:boolean};setStandalone(matchMedia("(display-mode: standalone)").matches||nav.standalone===true);setIos(/iphone|ipad|ipod/i.test(navigator.userAgent));setPermission("Notification" in window?Notification.permission:"unsupported");fetch("/api/notifications").then(r=>r.ok?r.json():null).then(r=>{if(r?.data?.preferences)setPrefs(r.data.preferences)}).catch(()=>setMessage("No pudimos cargar tus preferencias."));const capture=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt)};window.addEventListener("beforeinstallprompt",capture);return()=>window.removeEventListener("beforeinstallprompt",capture)},[]);
 async function install(){if(!prompt)return;await prompt.prompt();await prompt.userChoice;setPrompt(null)}
 async function ensureSubscription(){if(!("serviceWorker" in navigator)||!("PushManager" in window)||!vapidPublicKey)return false;const result=await Notification.requestPermission();setPermission(result);if(result!=="granted")return false;const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();subscription??=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(vapidPublicKey)});const response=await fetch("/api/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(subscription.toJSON())});return response.ok}
 async function toggle(intent:NotificationIntent){const next=!prefs[intent];setBusy(true);setMessage("");try{if(next&&!(await ensureSubscription())){setMessage(Notification.permission==="denied"?"Las notificaciones están bloqueadas en el navegador. Actívalas desde los permisos del sitio.":"No se pudo activar este dispositivo.");return}const response=await fetch("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({intent,enabled:next})});if(!response.ok)throw new Error();setPrefs(current=>({...current,[intent]:next}))}catch{setMessage("No pudimos guardar el cambio. Inténtalo de nuevo.")}finally{setBusy(false)}}
 const supported=permission!=="unsupported"&&Boolean(vapidPublicKey);
 return <>
  <section className="profile-group" aria-labelledby="install-title"><div className="profile-group-heading"><h2 id="install-title">Instalar Canastio</h2></div><div className="profile-list pwa-action"><div><strong>{standalone?"Aplicación instalada":"Acceso rápido desde tu dispositivo"}</strong><small>{standalone?"Estás usando Canastio en modo aplicación.":ios?"En Safari, pulsa Compartir → Añadir a pantalla de inicio.":prompt?"Instala Canastio para abrirlo como una aplicación.":"La instalación aparecerá cuando el navegador la permita."}</small></div>{!standalone&&prompt?<button className="primary-action" onClick={install}>Instalar</button>:null}</div></section>
  <section className="profile-group" aria-labelledby="notifications-title"><div className="profile-group-heading"><h2 id="notifications-title">Notificaciones</h2></div><p className="settings-help">Elige qué avisos quieres recibir en este dispositivo.</p>{!supported?<p className="settings-status">Las notificaciones push no están disponibles en este navegador o todavía falta configurarlas.</p>:permission==="denied"?<p className="settings-status">Permiso bloqueado. Puedes recuperarlo desde los ajustes del sitio.</p>:null}{message?<p className="form-message error" role="status">{message}</p>:null}
  {Object.entries(NOTIFICATION_GROUPS).map(([group,intents])=><div key={group} className="notification-group"><h3>{group}</h3><div className="profile-list">{intents.map(intent=><label className="notification-row" key={intent}><span>{LABELS[intent]}</span><input type="checkbox" role="switch" checked={Boolean(prefs[intent])&&permission!=="denied"} disabled={busy||!supported||permission==="denied"} onChange={()=>toggle(intent)}/></label>)}</div></div>)}</section>
 </>
}
