import { changeEmail, changePassword, deleteAccount, revokeOtherSessions, updateDiscovery } from "./security-actions";

export function SecuritySettings({ email, username, discoverable, lastSignInAt, device, message }: { email: string; username: string | null; discoverable: boolean; lastSignInAt: string | null; device: string; message?: string }) {
  return <>
    {message ? <p className="form-message" role="status">{message}</p> : null}
    <section className="profile-group" aria-labelledby="security-title"><div className="profile-group-heading"><h2 id="security-title">Seguridad</h2></div><div className="account-security-grid">
      <form action={changeEmail} className="profile-form"><h3>Cambiar correo</h3><p>Tu correo actual ({email}) seguirá vigente hasta que confirmes el nuevo.</p><label>Nuevo correo<input name="email" type="email" autoComplete="email" required /></label><label>Contraseña actual<input name="currentPassword" type="password" autoComplete="current-password" minLength={8} required /></label><button className="primary-action">Solicitar cambio</button></form>
      <form action={changePassword} className="profile-form"><h3>Cambiar contraseña</h3><label>Contraseña actual<input name="currentPassword" type="password" autoComplete="current-password" minLength={8} required /></label><label>Nueva contraseña<input name="password" type="password" autoComplete="new-password" minLength={8} required /></label><label>Repite la contraseña<input name="passwordConfirm" type="password" autoComplete="new-password" minLength={8} required /></label><button className="primary-action">Cambiar contraseña</button></form>
    </div><div className="setting-row"><span><strong>Autenticación multifactor</strong><small>Alta, recuperación y desactivación todavía no disponibles.</small></span><span className="verified">Próximamente</span></div></section>
    <section className="profile-group" aria-labelledby="sessions-title"><div className="profile-group-heading"><h2 id="sessions-title">Sesiones</h2></div><div className="setting-row"><span><strong>Esta sesión · {device}</strong><small>Actividad {lastSignInAt ? new Intl.DateTimeFormat("es-ES", { dateStyle: "medium" }).format(new Date(lastSignInAt)) : "reciente"}</small></span><span className="verified">Actual</span></div><form action={revokeOtherSessions}><button>Revocar las demás sesiones</button></form></section>
    <section className="profile-group" aria-labelledby="privacy-title"><div className="profile-group-heading"><h2 id="privacy-title">Privacidad y datos</h2></div><form action={updateDiscovery} className="setting-row"><span><strong>Permitir que me encuentren por username</strong><small>Controla búsquedas e invitaciones nuevas; no cambia tus ligas actuales.</small></span><input name="discoverable" type="checkbox" defaultChecked={discoverable} aria-label="Permitir que me encuentren por username" /><button>Guardar</button></form><a className="setting-row" href="/api/account/export" download><span><strong>Exportar mis datos</strong><small>JSON documentado, sin secretos ni datos privados de terceros.</small></span><span>Descargar</span></a></section>
    <section className="profile-group danger-zone" aria-labelledby="danger-title"><div className="profile-group-heading"><h2 id="danger-title">Zona de peligro</h2></div><p>Eliminar tu cuenta revoca el acceso y anonimiza tus datos personales. El histórico competitivo imprescindible se conserva sin identificarte.</p><form action={deleteAccount} className="profile-form"><label>Escribe tu username para confirmar<input name="confirmation" autoComplete="off" placeholder={username ?? "username"} required /></label><label>Contraseña actual<input name="currentPassword" type="password" autoComplete="current-password" minLength={8} required /></label><button className="danger-action">Eliminar mi cuenta definitivamente</button></form></section>
  </>;
}
