"use client";
import { useState } from "react";
type State = "PREVIEW" | "OPEN";
export function RolloutControl({ initialState, initialVersion, available }: { initialState: State; initialVersion: number; available: boolean }) {
  const [state, setState] = useState(initialState), [version, setVersion] = useState(initialVersion), [message, setMessage] = useState(available ? "" : "No se pudo leer la configuración. Se aplica PREVIEW de forma segura."), [pending, setPending] = useState(false);
  const next: State = state === "PREVIEW" ? "OPEN" : "PREVIEW";
  async function change() { const warning = next === "OPEN" ? "Abrir Canastio permitirá a todos los usuarios acceder al producto completo." : "Activar la preview bloqueará el producto para las cuentas públicas."; if (!window.confirm(`${warning}\n\n¿Continuar?`)) return; setPending(true); setMessage(""); const response = await fetch("/api/admin/rollout", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ state: next, version }) }); const body = await response.json() as { data?: { state: State; version: number }; error?: string }; setPending(false); if (!response.ok || !body.data) { setMessage(body.error === "ROLLOUT_VERSION_CONFLICT" ? "El estado cambió en otra sesión. Recarga antes de reintentar." : "No se pudo cambiar el acceso. El estado anterior sigue vigente."); return; } setState(body.data.state); setVersion(body.data.version); setMessage(body.data.state === "OPEN" ? "Canastio está abierto para todas las cuentas." : "La preview está activa; solo las cuentas internas acceden al producto completo."); }
  return <section className="profile-group rollout-control" aria-labelledby="rollout-title"><div><p className="eyebrow">Estado vigente</p><h2 id="rollout-title">{state === "PREVIEW" ? "Preview limitada" : "Acceso abierto"}</h2><p>{state === "PREVIEW" ? "El público puede registrarse y preparar su liga. El resto permanece bloqueado." : "Todas las cuentas autenticadas siguen el flujo normal de Canastio."}</p></div><div className="rollout-state" data-state={state}><span aria-hidden="true" />{state}</div><button className="primary-action" type="button" onClick={change} disabled={pending}>{pending ? "Guardando…" : next === "OPEN" ? "Abrir Canastio" : "Activar preview"}</button>{message ? <p className="settings-status" role="status">{message}</p> : null}</section>;
}
