import { notFound } from "next/navigation";
import { createClient } from "../../../../src/lib/supabase/server";
import { AdminError, getIngestionDashboard, listRawPayloads, requireIngestionAdmin } from "../../../../src/server/ingestion-admin";
import { AdminRefresh } from "./admin-refresh";
import { JobForm } from "./job-form";
import { RawViewer } from "./raw-viewer";
import { CatalogMonitorButton } from "./catalog-monitor-button";
import { CatalogSyncButton } from "./catalog-sync-button";
import { CompetitionTeamIndex } from "./competition-team-index";
const dt=new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Madrid"});
type Params={status?:string;type?:string;competitionSeasonId?:string;catalogQuery?:string;catalogStatus?:string;delegation?:string;season?:string};
export default async function IngestionAdminPage({searchParams}:{searchParams:Promise<Params>}){
 const {data:{user}}=await(await createClient()).auth.getUser();if(!user)notFound();let actor:string;try{actor=await requireIngestionAdmin(user.id)}catch(error){if(error instanceof AdminError&&error.status===404)notFound();throw error}
 const filters=await searchParams,[data,raw]=await Promise.all([getIngestionDashboard(actor,filters),listRawPayloads()]);const active=data.jobs.some(job=>job.status==="QUEUED"||job.status==="RUNNING");
 return <main className="app-main admin-page"><AdminRefresh active={active}/><header className="workspace-header"><div><p className="eyebrow">Operaciones</p><h1>Ingesta FAB</h1></div><span className={`health health-${data.health.toLowerCase()}`}>{data.health}</span></header>
 <section className="admin-summary"><div><small>Último heartbeat</small><strong>{data.heartbeat?dt.format(data.heartbeat.seenAt):"Sin señal"}</strong></div><div><small>Último ciclo correcto</small><strong>{data.lastSuccess?.finishedAt?dt.format(data.lastSuccess.finishedAt):"Sin datos"}</strong></div><div><small>Trabajos activos</small><strong>{data.jobs.filter(job=>["QUEUED","RUNNING"].includes(job.status)).length}</strong></div></section>
 <section className="profile-group"><h2>Competiciones monitorizadas</h2>{data.catalogScan?<p className="live-status">Último barrido: <strong>{data.catalogScan.status}</strong> · {dt.format(data.catalogScan.startedAt)} · {data.catalogScan.observed} observadas · {data.catalogScan.discovered} nuevas · {data.catalogScan.changed} cambios</p>:<p className="inline-alert">El catálogo global todavía no se ha comprobado.</p>}<div className="admin-table">{data.catalog.filter(item=>item.monitored).map(item=><CatalogRow item={item} jobs={data.jobs} teamIndex={data.teamIndexes.find(index=>index.catalogId===item.id)??null} key={item.id}/>)}</div></section>
 <section className="profile-group"><h2>Catálogo FAB</h2><form className="admin-filters"><input name="catalogQuery" aria-label="Buscar en catálogo" defaultValue={filters.catalogQuery??""} placeholder="Nombre o ID FAB"/><select name="catalogStatus" aria-label="Estado del catálogo" defaultValue={filters.catalogStatus??""}><option value="">Todos los estados</option>{["DISCOVERED","UNCHANGED","CHANGED","STALE","PARTIAL","FAILED"].map(value=><option key={value}>{value}</option>)}</select><select name="delegation" aria-label="Delegación" defaultValue={filters.delegation??""}><option value="">Todas las delegaciones</option>{data.delegations.map(value=><option key={value}>{value}</option>)}</select><select name="season" aria-label="Temporada" defaultValue={filters.season??""}><option value="">Todas las temporadas</option>{data.seasons.map(value=><option key={value}>{value}</option>)}</select><button>Filtrar</button></form><div className="admin-table">{data.catalog.length?data.catalog.map(item=><CatalogRow item={item} jobs={data.jobs} teamIndex={data.teamIndexes.find(index=>index.catalogId===item.id)??null} key={item.id}/>):<p>Sin competiciones para estos filtros.</p>}</div></section>
 <section className="profile-group"><h2>Relanzar ingesta</h2><JobForm/></section>
 <section className="profile-group"><h2>Trabajos recientes</h2><form className="admin-filters"><select name="status" aria-label="Estado del trabajo" defaultValue={filters.status??""}><option value="">Todos los estados</option>{["QUEUED","RUNNING","SUCCEEDED","FAILED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select><select name="type" aria-label="Tipo de trabajo" defaultValue={filters.type??""}><option value="">Todos los tipos</option>{["GAME","ROUND","COMPETITION"].map(value=><option key={value}>{value}</option>)}</select><input name="competitionSeasonId" aria-label="ID de competición" defaultValue={filters.competitionSeasonId??""} placeholder="UUID competición"/><button>Filtrar</button></form><div className="admin-table">{data.jobs.length?data.jobs.map(job=><article key={job.id}><strong>{job.type} · {job.targetKey}</strong><span>{job.effectiveStatus}</span><small>{dt.format(job.requestedAt)} · {job.errorCode??"Sin error"}</small></article>):<p>No hay trabajos para estos filtros.</p>}</div></section>
 <section className="profile-group"><h2>Ejecuciones</h2><div className="admin-table">{data.runs.map(run=><article key={run.id}><strong>{run.jobName}</strong><span>{run.status}</span><small>{dt.format(run.startedAt)} · {run.errorCategory??"Sin error"}</small></article>)}</div></section>
 <section className="profile-group"><h2>Payloads RAW recientes</h2><div className="admin-table">{raw.map(item=><article key={item.id}><strong>{item.entityType} · {item.externalId??"sin ID"}</strong><span>HTTP {item.httpStatus}</span><small>{dt.format(item.retrievedAt)} · {item.endpoint}</small><RawViewer id={item.id}/></article>)}</div></section></main>
}

type CatalogItem=Awaited<ReturnType<typeof getIngestionDashboard>>["catalog"][number];
type Job=Awaited<ReturnType<typeof getIngestionDashboard>>["jobs"][number];
type TeamIndex=Awaited<ReturnType<typeof getIngestionDashboard>>["teamIndexes"][number];
function CatalogRow({item,jobs,teamIndex}:{item:CatalogItem;jobs:Job[];teamIndex:TeamIndex|null}){const games=item.competitionSeason?.games??[],next=games.filter(game=>game.scheduledAt&&game.scheduledAt>new Date()).sort((a,b)=>a.scheduledAt!.getTime()-b.scheduledAt!.getTime())[0],mismatch=Boolean(item.competitionSeason?.name&&item.competitionSeason.name!==item.competitionName),rounds=new Set(games.map(game=>game.roundNumber).filter(Boolean)).size,lastJob=jobs.find(job=>job.targetKey===`categoryId:${item.categoryCompetitionId}`&&job.type==="COMPETITION"),jobActive=lastJob?.status==="QUEUED"||lastJob?.status==="RUNNING";return <article><strong>{item.alias??item.competitionName}</strong><span>{item.status}</span><small>{item.categoryName} · {item.delegationName}<br/>FAB {item.categoryCompetitionId} · primera vez {dt.format(item.firstSeenAt)} · comprobado {dt.format(item.lastCheckedAt)} · cambió {dt.format(item.lastChangedAt)}<br/>Checksum {item.checksum.slice(0,12)}…{mismatch?<><br/>⚠ Nombre interno: {item.competitionSeason?.name}</>:null}{item.competitionSeason?<><br/>{rounds} jornadas · {games.length} partidos · {games.filter(game=>game.status==="scheduled").length} programados · {games.filter(game=>game.status==="live").length} en directo · {games.filter(game=>game.status==="finished").length} finalizados · {games.filter(game=>game.statsSyncStatus==="pending").length} pendientes · {games.filter(game=>game.statsSyncStatus==="stats_final").length} stats final{next?` · próximo ${dt.format(next.scheduledAt!)}`:""}</>:null}{lastJob?<><br/>Último job: {lastJob.effectiveStatus} · {lastJob.errorCode??"sin error"}</>:null}</small><CatalogMonitorButton id={item.id} monitored={item.monitored}/>{item.monitored?<CatalogSyncButton categoryId={item.categoryCompetitionId} active={jobActive}/>:null}{item.monitored&&teamIndex?<CompetitionTeamIndex catalogId={item.id} initial={teamIndex}/>:null}</article>}
