import { describe, expect, it } from "vitest";
import { classifyError, MemorySink, Observability, redact, stableClientSignature } from "./observability";
describe("observability contract",()=>{
 it("classifies every origin unambiguously",()=>{expect(["FAB","POSTGRESQL","WEB","INGESTOR","CLIENT"].map(value=>classifyError(value as never))).toEqual(["FAB_TRANSPORT","DATABASE","WEB_APPLICATION","INGESTOR_FAILURE","CLIENT_ERROR"])});
 it("redacts canaries before a deterministic sink and groups by release",()=>{const sink=new MemorySink(),obs=new Observability(sink,true,()=>new Date("2026-09-14T00:00:00Z"),"r1","test"),canary="CANARY-SECRET";obs.emit({component:"WEB",operation:"request.failed",result:"ERROR",errorCategory:"WEB_APPLICATION",dimensions:{route:"/app?token="+canary,password:canary,email:canary,rawPayload:canary,userId:canary}});obs.emit({component:"WEB",operation:"request.failed",result:"ERROR",errorCategory:"WEB_APPLICATION"});expect(sink.signals.at(-1)?.count).toBe(2);expect(JSON.stringify(sink.signals)).not.toContain(canary);expect(sink.signals[0]).toMatchObject({schemaVersion:"canastio.observability.v1",release:"r1",environment:"test",component:"WEB",operation:"request.failed",result:"ERROR",errorCategory:"WEB_APPLICATION"})});
 it("never affects product flow when sink throws or is absent",()=>{const broken={write(){throw new Error("down")}};expect(()=>new Observability(broken).emit({component:"WEB",operation:"request",result:"ERROR",errorCategory:"WEB_APPLICATION"})).not.toThrow();expect(()=>new Observability().emit({component:"WEB",operation:"request",result:"ERROR",errorCategory:"WEB_APPLICATION"})).not.toThrow()});
 it("uses stable client signatures without dynamic content",()=>{expect(stableClientSignature("TypeError","render","r1")).toBe(stableClientSignature("TypeError","render","r1"));expect(stableClientSignature("TypeError","render","r1")).not.toContain("TypeError")});
 it("only admits bounded aggregate dimensions",()=>expect(redact({route:"/app?q=private",method:"GET",leagueName:"private",userId:"uuid",formBody:"secret"})).toEqual({route:"/app",method:"GET"}));
});
