"use client";
import { FormEvent, useState } from "react";
type Preview={revision:{id:string;fieldName:string;sourceType:string};label:string;diff:{before:unknown;after:unknown};impact:{roundNumber:number|null;recomputes:string[]}};
const gameFields=["scheduledAt","status","sourceStatus","homeScore","awayScore","hasStatistics"];
const statFields=["starter","minutesPlayed","millisecondsPlayed","points","freeThrowsMade","freeThrowsAttempted","twoPointersMade","twoPointersAttempted","threePointersMade","threePointersAttempted","offensiveRebounds","defensiveRebounds","rebounds","assists","steals","turnovers","blocks","blocksReceived","foulsCommitted","foulsReceived","technicalFouls","valuation","plusMinus"];
export function RevisionForm(){const[target,setTarget]=useState("GAME"),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const data=new FormData(event.currentTarget);const response=await fetch("/api/admin/revisions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetType:target,targetId:data.get("targetId"),sourceType:data.get("sourceType"),fieldName:data.get("fieldName"),value:data.get("value"),internalReason:data.get("internalReason"),publicReason:data.get("publicReason"),idempotencyKey:crypto.randomUUID()})});const body=await response.json();setBusy(false);if(!response.ok){setMessage(body.error??"No se pudo preparar la corrección");return}setPreview(body);}
 async function apply(){if(!preview||!confirm("Esta corrección modificará datos deportivos y recalculará sus resultados dependientes. ¿Continuar?"))return;setBusy(true);const response=await fetch(`/api/admin/revisions/${preview.revision.id}/apply`,{method:"POST"});const body=await response.json();setBusy(false);if(!response.ok){setMessage(body.error??"No se pudo aplicar");return}setMessage(body.replayed?"La revisión ya estaba aplicada.":"Corrección aplicada y derivados recalculados.");setPreview(null);location.reload();}
 const fields=target==="GAME"?gameFields:statFields;return <><form className="revision-form" onSubmit={submit}><label>Recurso<select value={target} onChange={event=>{setTarget(event.target.value);setPreview(null)}}><option value="GAME">Partido</option><option value="PLAYER_GAME_STAT">Estadística de jugador</option></select></label><label>ID interno<input required name="targetId" placeholder="UUID"/></label><label>Origen<select name="sourceType"><option value="SOURCE_CORRECTION">Corrección de FAB</option><option value="MANUAL_OVERRIDE">Override manual</option></select></label><label>Campo<select name="fieldName">{fields.map(field=><option key={field}>{field}</option>)}</select></label><label>Nuevo valor<input required name="value"/></label><label className="revision-wide">Motivo interno<textarea required minLength={8} name="internalReason" rows={3}/></label><label className="revision-wide">Motivo público opcional<input name="publicReason" maxLength={240}/></label><button className="primary-action" disabled={busy}>{busy?"Comprobando…":"Preparar vista previa"}</button></form>{message?<p className="settings-status" role="status">{message}</p>:null}{preview?<section className="revision-preview"><p className="eyebrow">Confirmación pendiente</p><h3>{preview.label}</h3><dl><div><dt>Campo</dt><dd>{preview.revision.fieldName}</dd></div><div><dt>Antes</dt><dd>{String(preview.diff.before??"null")}</dd></div><div><dt>Después</dt><dd>{String(preview.diff.after??"null")}</dd></div><div><dt>Impacto</dt><dd>{preview.impact.roundNumber?`Jornada ${preview.impact.roundNumber} · ${preview.impact.recomputes.join(", ")}`:"Sin jornada recalculable"}</dd></div></dl><button className="primary-action" disabled={busy} onClick={apply}>Confirmar y aplicar</button></section>:null}</>}
